//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProSymbolEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProSymbolEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://esriurl.com/AFDMilitaryOverlay.
        /// </summary>
        public static string AbtWinAFDUrl {
            get {
                return ResourceManager.GetString("AbtWinAFDUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Military Symbol Editor is a tool for quickly creating military overlays in ArcGIS Pro using the Military Overlay template. The tool is useful for searching, modifying attributes, and previewing military symbols. These military symbols can then be added to the map through map click or entering coordinates. The Military Symbol Editor is intended to be used with the ArcGIS for Defense Military Overlay Template or the Military Overlay Information Model..
        /// </summary>
        public static string AbtWinDescTxt {
            get {
                return ResourceManager.GetString("AbtWinDescTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Overlay Information Model.
        /// </summary>
        public static string AbtWinMilOvrInf {
            get {
                return ResourceManager.GetString("AbtWinMilOvrInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://esriurl.com/MilitaryOverlayInformationModel.
        /// </summary>
        public static string AbtWinMilOvrInfUrl {
            get {
                return ResourceManager.GetString("AbtWinMilOvrInfUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Overlay Template.
        /// </summary>
        public static string AbtWinMilOvrTmp {
            get {
                return ResourceManager.GetString("AbtWinMilOvrTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Symbol Editor.
        /// </summary>
        public static string AbtWinMilSymTxt {
            get {
                return ResourceManager.GetString("AbtWinMilSymTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string AbtWinResTxt {
            get {
                return ResourceManager.GetString("AbtWinResTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AbtWinTitle {
            get {
                return ResourceManager.GetString("AbtWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string btnBrowse {
            get {
                return ResourceManager.GetString("btnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Coordinate(s) to Map.
        /// </summary>
        public static string CoordBtnAddCoordinate {
            get {
                return ResourceManager.GetString("CoordBtnAddCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Favorite.
        /// </summary>
        public static string CoordBtnAddFavorite {
            get {
                return ResourceManager.GetString("CoordBtnAddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Label.
        /// </summary>
        public static string CoordBtnBack2LblToolTip {
            get {
                return ResourceManager.GetString("CoordBtnBack2LblToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark/Pan to Coordinate.
        /// </summary>
        public static string CoordBtnMarkPan {
            get {
                return ResourceManager.GetString("CoordBtnMarkPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Edits.
        /// </summary>
        public static string CoordBtnSaveEdits {
            get {
                return ResourceManager.GetString("CoordBtnSaveEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Edits.
        /// </summary>
        public static string CoordBtnSaveEditsToolTip {
            get {
                return ResourceManager.GetString("CoordBtnSaveEditsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string CoordDGHeaderAttr {
            get {
                return ResourceManager.GetString("CoordDGHeaderAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Coordinates.
        /// </summary>
        public static string CoordDGHeaderListOfCoords {
            get {
                return ResourceManager.GetString("CoordDGHeaderListOfCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string CoordDGHeaderVal {
            get {
                return ResourceManager.GetString("CoordDGHeaderVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        public static string CoordLblCoordinates {
            get {
                return ResourceManager.GetString("CoordLblCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Image to Clipboard.
        /// </summary>
        public static string CoordMenuCopyImage {
            get {
                return ResourceManager.GetString("CoordMenuCopyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image As....
        /// </summary>
        public static string CoordMenuSaveImage {
            get {
                return ResourceManager.GetString("CoordMenuSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinates are invalid.
        /// </summary>
        public static string CoordObjInvalidCoordinates {
            get {
                return ResourceManager.GetString("CoordObjInvalidCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Add to Map .
        /// </summary>
        public static string CoordToggleBtnAddMap {
            get {
                return ResourceManager.GetString("CoordToggleBtnAddMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Map.
        /// </summary>
        public static string CoordToggleBtnAddMapToolTip {
            get {
                return ResourceManager.GetString("CoordToggleBtnAddMapToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app6b.
        /// </summary>
        public static string Enumapp6b {
            get {
                return ResourceManager.GetString("Enumapp6b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app6d.
        /// </summary>
        public static string Enumapp6d {
            get {
                return ResourceManager.GetString("Enumapp6d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mil2525b.
        /// </summary>
        public static string Enummil2525b {
            get {
                return ResourceManager.GetString("Enummil2525b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mil2525c.
        /// </summary>
        public static string Enummil2525c {
            get {
                return ResourceManager.GetString("Enummil2525c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mil2525d.
        /// </summary>
        public static string Enummil2525d {
            get {
                return ResourceManager.GetString("Enummil2525d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Favorite.
        /// </summary>
        public static string FavBtnAddFavorite {
            get {
                return ResourceManager.GetString("FavBtnAddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Search.
        /// </summary>
        public static string FavBtnBack2Search {
            get {
                return ResourceManager.GetString("FavBtnBack2Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string FavBtnCreateTxt {
            get {
                return ResourceManager.GetString("FavBtnCreateTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Symbol Tab.
        /// </summary>
        public static string FavBtnGo2SymbolToolTip {
            get {
                return ResourceManager.GetString("FavBtnGo2SymbolToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import....
        /// </summary>
        public static string FavBtnImport {
            get {
                return ResourceManager.GetString("FavBtnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string FavBtnSaveAs {
            get {
                return ResourceManager.GetString("FavBtnSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string FavBtnTemplateTxt {
            get {
                return ResourceManager.GetString("FavBtnTemplateTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string FavDGHeaderAttr {
            get {
                return ResourceManager.GetString("FavDGHeaderAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string FavDGHeaderVal {
            get {
                return ResourceManager.GetString("FavDGHeaderVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By....
        /// </summary>
        public static string FavLblFilterBy {
            get {
                return ResourceManager.GetString("FavLblFilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Image to Clipboard.
        /// </summary>
        public static string FavMenuCopyImage {
            get {
                return ResourceManager.GetString("FavMenuCopyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image As....
        /// </summary>
        public static string FavMenuSaveImage {
            get {
                return ResourceManager.GetString("FavMenuSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Map.
        /// </summary>
        public static string FavToggleBtnAddMap {
            get {
                return ResourceManager.GetString("FavToggleBtnAddMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Map.
        /// </summary>
        public static string FavToggleBtnAddMapToolTip {
            get {
                return ResourceManager.GetString("FavToggleBtnAddMapToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label entered is at the maximum allowable length for this feature field.
        /// </summary>
        public static string LabelAttrLenError {
            get {
                return ResourceManager.GetString("LabelAttrLenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Attributes.
        /// </summary>
        public static string LabelAttrToString {
            get {
                return ResourceManager.GetString("LabelAttrToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Favorite.
        /// </summary>
        public static string LabelBtnAddFavorite {
            get {
                return ResourceManager.GetString("LabelBtnAddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Symbol.
        /// </summary>
        public static string LabelBtnBack2Symbol {
            get {
                return ResourceManager.GetString("LabelBtnBack2Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Coordinates.
        /// </summary>
        public static string LabelBtnEnterCoords {
            get {
                return ResourceManager.GetString("LabelBtnEnterCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Edits.
        /// </summary>
        public static string LabelBtnSaveEdits {
            get {
                return ResourceManager.GetString("LabelBtnSaveEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Edits.
        /// </summary>
        public static string LabelBtnSaveEditsToolTip {
            get {
                return ResourceManager.GetString("LabelBtnSaveEditsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string LabelDGHeaderAttr {
            get {
                return ResourceManager.GetString("LabelDGHeaderAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string LabelDGHeaderVal {
            get {
                return ResourceManager.GetString("LabelDGHeaderVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string LabelLblAdditionalInfo {
            get {
                return ResourceManager.GetString("LabelLblAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Identifier.
        /// </summary>
        public static string LabelLblCommonIdentifier {
            get {
                return ResourceManager.GetString("LabelLblCommonIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string LabelLblCountryCode {
            get {
                return ResourceManager.GetString("LabelLblCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credibility.
        /// </summary>
        public static string LabelLblCredibility {
            get {
                return ResourceManager.GetString("LabelLblCredibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time Expired.
        /// </summary>
        public static string LabelLblDateTimeExpired {
            get {
                return ResourceManager.GetString("LabelLblDateTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time Valid.
        /// </summary>
        public static string LabelLblDateTimeValid {
            get {
                return ResourceManager.GetString("LabelLblDateTimeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string LabelLblDirection {
            get {
                return ResourceManager.GetString("LabelLblDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher Formation.
        /// </summary>
        public static string LabelLblHigherForm {
            get {
                return ResourceManager.GetString("LabelLblHigherForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforced.
        /// </summary>
        public static string LabelLblReinforced {
            get {
                return ResourceManager.GetString("LabelLblReinforced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliability.
        /// </summary>
        public static string LabelLblReliability {
            get {
                return ResourceManager.GetString("LabelLblReliability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Equipment(ENY).
        /// </summary>
        public static string LabelLblSignatureEquipment {
            get {
                return ResourceManager.GetString("LabelLblSignatureEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string LabelLblSpeed {
            get {
                return ResourceManager.GetString("LabelLblSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Comments.
        /// </summary>
        public static string LabelLblStaffComments {
            get {
                return ResourceManager.GetString("LabelLblStaffComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string LabelLblType {
            get {
                return ResourceManager.GetString("LabelLblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Designation.
        /// </summary>
        public static string LabelLblUniqueDesignation {
            get {
                return ResourceManager.GetString("LabelLblUniqueDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Image to Clipboard.
        /// </summary>
        public static string LabelMenuCopyImage {
            get {
                return ResourceManager.GetString("LabelMenuCopyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image As....
        /// </summary>
        public static string LabelMenuSaveImage {
            get {
                return ResourceManager.GetString("LabelMenuSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Add to Map .
        /// </summary>
        public static string LabelToggleBtnAddMap {
            get {
                return ResourceManager.GetString("LabelToggleBtnAddMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Map.
        /// </summary>
        public static string LabelToggleBtnAddMapToolTip {
            get {
                return ResourceManager.GetString("LabelToggleBtnAddMapToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in Not Enabled.
        /// </summary>
        public static string MilSymDPAddInDisabled {
            get {
                return ResourceManager.GetString("MilSymDPAddInDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-In Disabled.
        /// </summary>
        public static string MilSymDPAddInDisabledCaption {
            get {
                return ResourceManager.GetString("MilSymDPAddInDisabledCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Layer to Map?.
        /// </summary>
        public static string MilSymDPAddLyrCaption {
            get {
                return ResourceManager.GetString("MilSymDPAddLyrCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD MAP TO PROJECT.
        /// </summary>
        public static string MilSymDPAddMap {
            get {
                return ResourceManager.GetString("MilSymDPAddMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Add Map to Your Project.
        /// </summary>
        public static string MilSymDPAddMapCaption {
            get {
                return ResourceManager.GetString("MilSymDPAddMapCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Schema to Database.
        /// </summary>
        public static string MilSymDPAddSchemaDbCaption {
            get {
                return ResourceManager.GetString("MilSymDPAddSchemaDbCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to affiliation.
        /// </summary>
        public static string MilSymDPAffiliationFld {
            get {
                return ResourceManager.GetString("MilSymDPAffiliationFld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identity.
        /// </summary>
        public static string MilSymDPAffiliationFldDef {
            get {
                return ResourceManager.GetString("MilSymDPAffiliationFldDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings Read-Only.
        /// </summary>
        public static string MilSymDPAppSettingsCaption {
            get {
                return ResourceManager.GetString("MilSymDPAppSettingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt Favorites Files.
        /// </summary>
        public static string MilSymDPCorruptFavrCaption {
            get {
                return ResourceManager.GetString("MilSymDPCorruptFavrCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Create Map Feature.
        /// </summary>
        public static string MilSymDPCouldNotCreateMapFeaCaption {
            get {
                return ResourceManager.GetString("MilSymDPCouldNotCreateMapFeaCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Open Database.
        /// </summary>
        public static string MilSymDPCouldNotOpenDbCaption {
            get {
                return ResourceManager.GetString("MilSymDPCouldNotOpenDbCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Symbol Insert.
        /// </summary>
        public static string MilSymDPEdMilSymInsert {
            get {
                return ResourceManager.GetString("MilSymDPEdMilSymInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click to enable add-in....
        /// </summary>
        public static string MilSymDPEnableAddIn {
            get {
                return ResourceManager.GetString("MilSymDPEnableAddIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Adding Favorite.
        /// </summary>
        public static string MilSymDPErrorAddFavrCaption {
            get {
                return ResourceManager.GetString("MilSymDPErrorAddFavrCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught: .
        /// </summary>
        public static string MilSymDPExcCaught {
            get {
                return ResourceManager.GetString("MilSymDPExcCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinates are invalid.
        /// </summary>
        public static string MilSymDPExcInvalidCoordinates {
            get {
                return ResourceManager.GetString("MilSymDPExcInvalidCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in SelectedSelectedFeature: .
        /// </summary>
        public static string MilSymDPExcSelectedFeature {
            get {
                return ResourceManager.GetString("MilSymDPExcSelectedFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extendedfunctioncode.
        /// </summary>
        public static string MilSymDPExtFunctCode {
            get {
                return ResourceManager.GetString("MilSymDPExtFunctCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Store Failure.
        /// </summary>
        public static string MilsymDPFeaStoreFail {
            get {
                return ResourceManager.GetString("MilsymDPFeaStoreFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Png Image|*.png.
        /// </summary>
        public static string MilSymDPFilterImagePNG {
            get {
                return ResourceManager.GetString("MilSymDPFilterImagePNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON|*.json.
        /// </summary>
        public static string MilSymDPFilterJSON {
            get {
                return ResourceManager.GetString("MilSymDPFilterJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        public static string MilSymDPFriend {
            get {
                return ResourceManager.GetString("MilSymDPFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly.
        /// </summary>
        public static string MilSymDPFriendly {
            get {
                return ResourceManager.GetString("MilSymDPFriendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRIEND.
        /// </summary>
        public static string MilSymDPFriendUpper {
            get {
                return ResourceManager.GetString("MilSymDPFriendUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostile.
        /// </summary>
        public static string MilSymDPHostile {
            get {
                return ResourceManager.GetString("MilSymDPHostile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostile/Faker.
        /// </summary>
        public static string MilSymDPHostileFaker {
            get {
                return ResourceManager.GetString("MilSymDPHostileFaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOSTILE.
        /// </summary>
        public static string MilSymDPHostileUpper {
            get {
                return ResourceManager.GetString("MilSymDPHostileUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .JSON.
        /// </summary>
        public static string MilSymDPImpExtJSON {
            get {
                return ResourceManager.GetString("MilSymDPImpExtJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Files (*.json)|*.json.
        /// </summary>
        public static string MilSymDPImpFilterJSON {
            get {
                return ResourceManager.GetString("MilSymDPImpFilterJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Favorite.
        /// </summary>
        public static string MilSymDPInvalidFavrCaption {
            get {
                return ResourceManager.GetString("MilSymDPInvalidFavrCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Selection.
        /// </summary>
        public static string MilSymDPInvalidSelectionCaption {
            get {
                return ResourceManager.GetString("MilSymDPInvalidSelectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echelon.
        /// </summary>
        public static string MilSymDPLblEchelon {
            get {
                return ResourceManager.GetString("MilSymDPLblEchelon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echelon/Mobility.
        /// </summary>
        public static string MilSymDPLblEchelonMobility {
            get {
                return ResourceManager.GetString("MilSymDPLblEchelonMobility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Layer Package....
        /// </summary>
        public static string MilSymDPLoadLyrPkg {
            get {
                return ResourceManager.GetString("MilSymDPLoadLyrPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Layers Added.
        /// </summary>
        public static string MilSymDPMilLyrAdded {
            get {
                return ResourceManager.GetString("MilSymDPMilLyrAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Overlay Removed.
        /// </summary>
        public static string MilSymDPMilOverlayRmvCaption {
            get {
                return ResourceManager.GetString("MilSymDPMilOverlayRmvCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add the data model (database schema and layers) to the project?.
        /// </summary>
        public static string MilSymDPMsgAddDataModel {
            get {
                return ResourceManager.GetString("MilSymDPMsgAddDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be added to database: .
        /// </summary>
        public static string MilSymDPMsgAddDb {
            get {
                return ResourceManager.GetString("MilSymDPMsgAddDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this military overlay layer to the map?.
        /// </summary>
        public static string MilSymDPMsgAddMilOverlayLyr {
            get {
                return ResourceManager.GetString("MilSymDPMsgAddMilOverlayLyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  so the Military Symbol Editor cannot continue. Would you like to add the Military Overlay Layer Package to your project?.
        /// </summary>
        public static string MilSymDPMsgAddMilOverlayLyrPkg {
            get {
                return ResourceManager.GetString("MilSymDPMsgAddMilOverlayLyrPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to )..
        /// </summary>
        public static string MilSymDPMsgCloseBracket {
            get {
                return ResourceManager.GetString("MilSymDPMsgCloseBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project already contains a database with schema for standard: .
        /// </summary>
        public static string MilSymDPMsgContainsDbSchema {
            get {
                return ResourceManager.GetString("MilSymDPMsgContainsDbSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        public static string MilSymDPMsgContinue {
            get {
                return ResourceManager.GetString("MilSymDPMsgContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create a new project to change these settings..
        /// </summary>
        public static string MilSymDPMsgCreateNewPrj {
            get {
                return ResourceManager.GetString("MilSymDPMsgCreateNewPrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database: .
        /// </summary>
        public static string MilSymDPMsgDb {
            get {
                return ResourceManager.GetString("MilSymDPMsgDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Added.
        /// </summary>
        public static string MilSymDPMsgDbAdded {
            get {
                return ResourceManager.GetString("MilSymDPMsgDbAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please delete the file and try again..
        /// </summary>
        public static string MilSymDPMsgDeleteFile {
            get {
                return ResourceManager.GetString("MilSymDPMsgDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialize failure: .
        /// </summary>
        public static string MilSymDPMsgDeserializeFailure {
            get {
                return ResourceManager.GetString("MilSymDPMsgDeserializeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a different database from Addin Settings..
        /// </summary>
        public static string MilSymDPMsgDiffDbAddInSettings {
            get {
                return ResourceManager.GetString("MilSymDPMsgDiffDbAddInSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string MilSymDPMsgEnd {
            get {
                return ResourceManager.GetString("MilSymDPMsgEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - the favorites file: .
        /// </summary>
        public static string MilSymDPMsgErrorFavrFile {
            get {
                return ResourceManager.GetString("MilSymDPMsgErrorFavrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already contains a schema for Military Overlay..
        /// </summary>
        public static string MilSymDPMsgHasMilOverlaySchema {
            get {
                return ResourceManager.GetString("MilSymDPMsgHasMilOverlaySchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized.
        /// </summary>
        public static string MilSymDPMsgInitialized {
            get {
                return ResourceManager.GetString("MilSymDPMsgInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import file you selected is invalid - please choose a valid JSON file..
        /// </summary>
        public static string MilSymDPMsgInvalidImportFile {
            get {
                return ResourceManager.GetString("MilSymDPMsgInvalidImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Layer Not Found}.
        /// </summary>
        public static string MilSymDPMsgLyrNotFound {
            get {
                return ResourceManager.GetString("MilSymDPMsgLyrNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project map is not currently available..
        /// </summary>
        public static string MilSymDPMsgMapNotAvailable {
            get {
                return ResourceManager.GetString("MilSymDPMsgMapNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure the project contains a map and the map is visible..
        /// </summary>
        public static string MilSymDPMsgMapVisible {
            get {
                return ResourceManager.GetString("MilSymDPMsgMapVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: wait for map to be visible and ready..
        /// </summary>
        public static string MilSymDPMsgMapVisibleReady {
            get {
                return ResourceManager.GetString("MilSymDPMsgMapVisibleReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Layers Added.
        /// </summary>
        public static string MilSymDPMsgMilLyrAdded {
            get {
                return ResourceManager.GetString("MilSymDPMsgMilLyrAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required Military Overlay layers have been removed from the active map..
        /// </summary>
        public static string MilSymDPMsgMilOverlayLyrRmvd {
            get {
                return ResourceManager.GetString("MilSymDPMsgMilOverlayLyrRmvd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A military overlay schema matching standard: .
        /// </summary>
        public static string MilSymDPMsgMilOverlaySchema {
            get {
                return ResourceManager.GetString("MilSymDPMsgMilOverlaySchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Military Overlay schema is not detected in any database in your project..
        /// </summary>
        public static string MilSymDPMsgMilOverlaySchemaNotDetected {
            get {
                return ResourceManager.GetString("MilSymDPMsgMilOverlaySchemaNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create Favorite..
        /// </summary>
        public static string MilSymDPMsgNotCreatedFavr {
            get {
                return ResourceManager.GetString("MilSymDPMsgNotCreatedFavr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Create Template.
        /// </summary>
        public static string MilSymDPMsgNotCreatedTemplate {
            get {
                return ResourceManager.GetString("MilSymDPMsgNotCreatedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create map feature in layer: .
        /// </summary>
        public static string MilSymDPMsgNotCreateFeaLyr {
            get {
                return ResourceManager.GetString("MilSymDPMsgNotCreateFeaLyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) is not detected in Pro Install..
        /// </summary>
        public static string MilSymDPMsgNotDetected {
            get {
                return ResourceManager.GetString("MilSymDPMsgNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could not be loaded..
        /// </summary>
        public static string MilSymDPMsgNotLoaded {
            get {
                return ResourceManager.GetString("MilSymDPMsgNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Selected Feature does not seem to be a Military Feature or does not match the Military Standard in use (.
        /// </summary>
        public static string MilSymDPMsgNotMatchMilStandard {
            get {
                return ResourceManager.GetString("MilSymDPMsgNotMatchMilStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open Database: .
        /// </summary>
        public static string MilSymDPMsgNotOpenDb {
            get {
                return ResourceManager.GetString("MilSymDPMsgNotOpenDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current favorite is not valid..
        /// </summary>
        public static string MilSymDPMsgNotValidFavr {
            get {
                return ResourceManager.GetString("MilSymDPMsgNotValidFavr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project does not contain any active map.  Create one and try again..
        /// </summary>
        public static string MilSymDPMsgPrjMapNotActive {
            get {
                return ResourceManager.GetString("MilSymDPMsgPrjMapNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required layer: .
        /// </summary>
        public static string MilSymDPMsgReqLyr {
            get {
                return ResourceManager.GetString("MilSymDPMsgReqLyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required layer is not in the Active Map. .
        /// </summary>
        public static string MilSymDPMsgReqLyrNotActive {
            get {
                return ResourceManager.GetString("MilSymDPMsgReqLyrNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Military Symbol Editor requires the Military Overlay data model..
        /// </summary>
        public static string MilSymDPMsgReqMilOverlayDataModel {
            get {
                return ResourceManager.GetString("MilSymDPMsgReqMilOverlayDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Required Military Style (.
        /// </summary>
        public static string MilSymDPMsgReqMilStyle {
            get {
                return ResourceManager.GetString("MilSymDPMsgReqMilStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Military Symbol Editor has been reset..
        /// </summary>
        public static string MilSymDPMsgReset {
            get {
                return ResourceManager.GetString("MilSymDPMsgReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing the required Military Overlay layers will reset the Military Symbol Editor..
        /// </summary>
        public static string MilSymDPMsgRmvMilOverlayLyr {
            get {
                return ResourceManager.GetString("MilSymDPMsgRmvMilOverlayLyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Complete.
        /// </summary>
        public static string MilSymDPMsgSrchComplete {
            get {
                return ResourceManager.GetString("MilSymDPMsgSrchComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: this may take several minutes..
        /// </summary>
        public static string MilSymDPMsgTakeSeveralMins {
            get {
                return ResourceManager.GetString("MilSymDPMsgTakeSeveralMins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        public static string MilSymDPMsgThe {
            get {
                return ResourceManager.GetString("MilSymDPMsgThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to try again?.
        /// </summary>
        public static string MilSymDPMsgTryAgain {
            get {
                return ResourceManager.GetString("MilSymDPMsgTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again from Addin Settings when map available..
        /// </summary>
        public static string MilSymDPMsgTryAgainAddInSettings {
            get {
                return ResourceManager.GetString("MilSymDPMsgTryAgainAddInSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add the current favorite. .
        /// </summary>
        public static string MilSymDPMsgUnable2AddFavr {
            get {
                return ResourceManager.GetString("MilSymDPMsgUnable2AddFavr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add layer package to map..
        /// </summary>
        public static string MilSymDPMsgUnable2AddLyrPkg {
            get {
                return ResourceManager.GetString("MilSymDPMsgUnable2AddLyrPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add layer package to map..
        /// </summary>
        public static string MilSymDPMsgUnableAddLyrPkg {
            get {
                return ResourceManager.GetString("MilSymDPMsgUnableAddLyrPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string MilSymDPNeutral {
            get {
                return ResourceManager.GetString("MilSymDPNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEUTRAL.
        /// </summary>
        public static string MilSymDPNeutralUpper {
            get {
                return ResourceManager.GetString("MilSymDPNeutralUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW_AT_2525D.
        /// </summary>
        public static string MilSymDPNEW2525D {
            get {
                return ResourceManager.GetString("MilSymDPNEW2525D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Create Template.
        /// </summary>
        public static string MilSymDPNotCreateTempCaption {
            get {
                return ResourceManager.GetString("MilSymDPNotCreateTempCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Adding Military Overlay Data Model?.
        /// </summary>
        public static string MilSymDPRetryAddingDataModelCaption {
            get {
                return ResourceManager.GetString("MilSymDPRetryAddingDataModelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Military Overlay?.
        /// </summary>
        public static string MilSymDPRmvMilOverlayCaption {
            get {
                return ResourceManager.GetString("MilSymDPRmvMilOverlayCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string MilSymDPSaveFavrs {
            get {
                return ResourceManager.GetString("MilSymDPSaveFavrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbol.
        /// </summary>
        public static string MilSymDPSaveSymbol {
            get {
                return ResourceManager.GetString("MilSymDPSaveSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string MilSymDPSrch {
            get {
                return ResourceManager.GetString("MilSymDPSrch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbolentity.
        /// </summary>
        public static string MilSymDPSymEntity {
            get {
                return ResourceManager.GetString("MilSymDPSymEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbolset.
        /// </summary>
        public static string MilSymDPSymSet {
            get {
                return ResourceManager.GetString("MilSymDPSymSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Add Layer Package to Map.
        /// </summary>
        public static string MilSymDPUnable2AddLyrPkgCaption {
            get {
                return ResourceManager.GetString("MilSymDPUnable2AddLyrPkgCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Select Database.
        /// </summary>
        public static string MilSymDPUnableSelectDbCaption {
            get {
                return ResourceManager.GetString("MilSymDPUnableSelectDbCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string MilSymDPUnk {
            get {
                return ResourceManager.GetString("MilSymDPUnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        public static string MiSymDPColon {
            get {
                return ResourceManager.GetString("MiSymDPColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Symbol Tab.
        /// </summary>
        public static string ModBtnGo2SymTabToolTip {
            get {
                return ResourceManager.GetString("ModBtnGo2SymTabToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string ModDGHeaderAttr {
            get {
                return ResourceManager.GetString("ModDGHeaderAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ModDGHeaderVal {
            get {
                return ResourceManager.GetString("ModDGHeaderVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the select tool to select a feature to modify.
        /// </summary>
        public static string ModLblSelectTool {
            get {
                return ResourceManager.GetString("ModLblSelectTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Image to Clipboard.
        /// </summary>
        public static string ModMenuCopyImage {
            get {
                return ResourceManager.GetString("ModMenuCopyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image As....
        /// </summary>
        public static string ModMenuSaveImage {
            get {
                return ResourceManager.GetString("ModMenuSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  : Object ID .
        /// </summary>
        public static string ModTxtObjectID {
            get {
                return ResourceManager.GetString("ModTxtObjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MsdBtnAbout {
            get {
                return ResourceManager.GetString("MsdBtnAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MsdBtnSettings {
            get {
                return ResourceManager.GetString("MsdBtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a feature to modify.
        /// </summary>
        public static string MsdLblSelectFeature {
            get {
                return ResourceManager.GetString("MsdLblSelectFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Coordinates.
        /// </summary>
        public static string MsdTabheaderEnterCoords {
            get {
                return ResourceManager.GetString("MsdTabheaderEnterCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string MsdTabHeaderFavorites {
            get {
                return ResourceManager.GetString("MsdTabHeaderFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string MsdTabHeaderLabel {
            get {
                return ResourceManager.GetString("MsdTabHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string MsdTabHeaderSearch {
            get {
                return ResourceManager.GetString("MsdTabHeaderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string MsdTabHeaderSymbol {
            get {
                return ResourceManager.GetString("MsdTabHeaderSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP-6(B).
        /// </summary>
        public static string PSymapp6b {
            get {
                return ResourceManager.GetString("PSymapp6b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP-6(D).
        /// </summary>
        public static string PSymapp6d {
            get {
                return ResourceManager.GetString("PSymapp6d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Geodatabase.
        /// </summary>
        public static string PSymBwItemGDB {
            get {
                return ResourceManager.GetString("PSymBwItemGDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mil2525bc2.
        /// </summary>
        public static string PSymDic2525b {
            get {
                return ResourceManager.GetString("PSymDic2525b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mil2525c.
        /// </summary>
        public static string PSymDic2525c {
            get {
                return ResourceManager.GetString("PSymDic2525c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app6b.
        /// </summary>
        public static string PSymDicapp6b {
            get {
                return ResourceManager.GetString("PSymDicapp6b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app6d.
        /// </summary>
        public static string PSymDicapp6d {
            get {
                return ResourceManager.GetString("PSymDicapp6d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mil2525d.
        /// </summary>
        public static string PSymDicDef {
            get {
                return ResourceManager.GetString("PSymDicDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mil2525c_b2.
        /// </summary>
        public static string PSymDicOth {
            get {
                return ResourceManager.GetString("PSymDicOth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning - unable to execute command: .
        /// </summary>
        public static string PSymExcCmdWar {
            get {
                return ResourceManager.GetString("PSymExcCmdWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIL-STD-2525B w/ Change 2.
        /// </summary>
        public static string PSymmil2525b {
            get {
                return ResourceManager.GetString("PSymmil2525b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIL-STD-2525C.
        /// </summary>
        public static string PSymmil2525c {
            get {
                return ResourceManager.GetString("PSymmil2525c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIL-STD-2525D.
        /// </summary>
        public static string PSymmil2525d {
            get {
                return ResourceManager.GetString("PSymmil2525d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning - GetStandardFromLabel unrecognized standard string: .
        /// </summary>
        public static string PSymStFromLblMsg {
            get {
                return ResourceManager.GetString("PSymStFromLblMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP6B.
        /// </summary>
        public static string PSymStLblapp6b {
            get {
                return ResourceManager.GetString("PSymStLblapp6b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP6D.
        /// </summary>
        public static string PSymStLblapp6d {
            get {
                return ResourceManager.GetString("PSymStLblapp6d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2525D.
        /// </summary>
        public static string PSymStLblDef {
            get {
                return ResourceManager.GetString("PSymStLblDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2525B.
        /// </summary>
        public static string PSymStLblmil2525b {
            get {
                return ResourceManager.GetString("PSymStLblmil2525b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2525C.
        /// </summary>
        public static string PSymStLblmil2525c {
            get {
                return ResourceManager.GetString("PSymStLblmil2525c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Favorite.
        /// </summary>
        public static string SrchBtnAddFavorite {
            get {
                return ResourceManager.GetString("SrchBtnAddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Symbol Tab.
        /// </summary>
        public static string SrchBtnGo2SymTabToolTip {
            get {
                return ResourceManager.GetString("SrchBtnGo2SymTabToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string SrchBtnX {
            get {
                return ResourceManager.GetString("SrchBtnX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Count:.
        /// </summary>
        public static string SrchLblResultCount {
            get {
                return ResourceManager.GetString("SrchLblResultCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SrchLblSearch {
            get {
                return ResourceManager.GetString("SrchLblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string SrchMenuCopy {
            get {
                return ResourceManager.GetString("SrchMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Image to Clipboard.
        /// </summary>
        public static string SrchMenuCopyImage {
            get {
                return ResourceManager.GetString("SrchMenuCopyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image As....
        /// </summary>
        public static string SrchMenuSaveImage {
            get {
                return ResourceManager.GetString("SrchMenuSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Add to Map .
        /// </summary>
        public static string SrchToggleBtnAddMap {
            get {
                return ResourceManager.GetString("SrchToggleBtnAddMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Map.
        /// </summary>
        public static string SrchToggleBtnAddMapToolTip {
            get {
                return ResourceManager.GetString("SrchToggleBtnAddMapToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {default}.
        /// </summary>
        public static string SWDefaultDb {
            get {
                return ResourceManager.GetString("SWDefaultDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Contains Schema.
        /// </summary>
        public static string SWMsgCaption {
            get {
                return ResourceManager.GetString("SWMsgCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database: .
        /// </summary>
        public static string SWStDbMsg {
            get {
                return ResourceManager.GetString("SWStDbMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string SWStEndMsg {
            get {
                return ResourceManager.GetString("SWStEndMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains a schema for standard: .
        /// </summary>
        public static string SWStSchMsg {
            get {
                return ResourceManager.GetString("SWStSchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting standard to this value..
        /// </summary>
        public static string SWStSetMsg {
            get {
                return ResourceManager.GetString("SWStSetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Overlay _Database:.
        /// </summary>
        public static string SWWinMilOvrDBLbl {
            get {
                return ResourceManager.GetString("SWWinMilOvrDBLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Symbology _Standard:.
        /// </summary>
        public static string SWWinMilSymStLbl {
            get {
                return ResourceManager.GetString("SWWinMilSymStLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string SWWinTitle {
            get {
                return ResourceManager.GetString("SWWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in GetBitmapImageAsync: .
        /// </summary>
        public static string SymAttrGetBmpImgExc {
            get {
                return ResourceManager.GetString("SymAttrGetBmpImgExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Feature passed to PopulateFeatureWithAttributes.
        /// </summary>
        public static string SymAttrNullFeaPassed {
            get {
                return ResourceManager.GetString("SymAttrNullFeaPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null RowBuffer passed to PopulateRowBufferWithAttributes.
        /// </summary>
        public static string SymAttrNullRowBuffer {
            get {
                return ResourceManager.GetString("SymAttrNullRowBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Favorite.
        /// </summary>
        public static string SymBtnAddFavorite {
            get {
                return ResourceManager.GetString("SymBtnAddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Search.
        /// </summary>
        public static string SymBtnBack2SearchToolTip {
            get {
                return ResourceManager.GetString("SymBtnBack2SearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Label Tab.
        /// </summary>
        public static string SymBtnGo2LabelTabToolTip {
            get {
                return ResourceManager.GetString("SymBtnGo2LabelTabToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Edits.
        /// </summary>
        public static string SymBtnSaveEdits {
            get {
                return ResourceManager.GetString("SymBtnSaveEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Edits.
        /// </summary>
        public static string SymBtnSaveEditsToolTip {
            get {
                return ResourceManager.GetString("SymBtnSaveEditsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string SymDGHeaderAttr {
            get {
                return ResourceManager.GetString("SymDGHeaderAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string SymDGHeaderVal {
            get {
                return ResourceManager.GetString("SymDGHeaderVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        public static string SymLblContext {
            get {
                return ResourceManager.GetString("SymLblContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string SymLblEntity {
            get {
                return ResourceManager.GetString("SymLblEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string SymLblFunction {
            get {
                return ResourceManager.GetString("SymLblFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity/Affiliation.
        /// </summary>
        public static string SymLblIdentityAffiliation {
            get {
                return ResourceManager.GetString("SymLblIdentityAffiliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobility.
        /// </summary>
        public static string SymLblMobility {
            get {
                return ResourceManager.GetString("SymLblMobility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier 1.
        /// </summary>
        public static string SymLblModifier1 {
            get {
                return ResourceManager.GetString("SymLblModifier1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier 2.
        /// </summary>
        public static string SymLblModifier2 {
            get {
                return ResourceManager.GetString("SymLblModifier2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Condition.
        /// </summary>
        public static string SymLblOperCondititon {
            get {
                return ResourceManager.GetString("SymLblOperCondititon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status/Planned.
        /// </summary>
        public static string SymLblStatusPlanned {
            get {
                return ResourceManager.GetString("SymLblStatusPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF, FD, HQ.
        /// </summary>
        public static string SymLblTFFDHQ {
            get {
                return ResourceManager.GetString("SymLblTFFDHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Image to Clipboard.
        /// </summary>
        public static string SymMenuCopyImage {
            get {
                return ResourceManager.GetString("SymMenuCopyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image As....
        /// </summary>
        public static string SymMenuSaveImage {
            get {
                return ResourceManager.GetString("SymMenuSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFeatureClassFromExtendedFunctionCode - could not find feature class for: .
        /// </summary>
        public static string SymSetMapFCLNotFound {
            get {
                return ResourceManager.GetString("SymSetMapFCLNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Add to Map .
        /// </summary>
        public static string SymToggleBtnAddMap {
            get {
                return ResourceManager.GetString("SymToggleBtnAddMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Map.
        /// </summary>
        public static string SymToggleBtnAddMapToolTip {
            get {
                return ResourceManager.GetString("SymToggleBtnAddMapToolTip", resourceCulture);
            }
        }
    }
}
